# Generated by Django 6.0.4 on 2026-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('raza', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('cinta', 'En cinta'), ('vacunas', 'Vacunas'), ('enferma', 'Enferma'), ('produccion', 'Producción')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
